### ISSUE TITLE
Documentation under "Distributed configuration" does not resolve dependency

### ISSUE THREAD

**Issue by dfourmanfsquared** [micronaut-projects/micronaut-azure#357]
### Expected Behavior

add to gradle:
    implementation("io.micronaut.azure:micronaut-azure-sdk:3.3.0")
    implementation("io.micronaut.azure:micronaut-azure-secret-manager")
Add config specified in the docs, run the project, should fetch the secrets from the keyvault specified in the yaml

### Actual Behaviour

Dependency error for micronaut-azure-secret-manager
Could not find io.micronaut.azure:micronaut-azure-secret-manager:.
Required by:
    project :

### Steps To Reproduce

add to gradle:
    implementation("io.micronaut.azure:micronaut-azure-sdk:3.3.0")
    implementation("io.micronaut.azure:micronaut-azure-secret-manager")
Add config specified in the docs, run the project, should fetch the secrets from the keyvault specified in the yaml

### Environment Information

Windows 11
Zulu JDK 11
Gradle

### Version

3.5.1

**Comment by wetted** [comment]
I can duplicate this dependency resolution issue for v3.5.x, but it appears to work fine with Micronaut 3.6.0 and Micronaut 4.0.3.

@dfourmanfsquared Can you please update your project to Micronaut 3.6.0 or later (3.10.0 and 4.0.3 are latest) and confirm it's no longer a problem?

**Comment by wetted** [comment]
Not an issue as of Micronaut 3.6.0.
