### ISSUE TITLE
CosmosClientSpec not being run fails for MacOS, it is ignored in CI with linux

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-azure#549]
https://ge.micronaut.io/scans/tests?search.timeZoneId=Europe/Madrid&tests.container=io.micronaut.azure.cosmos.client.CosmosClientSpec

**Comment by sdelamo** [comment]
@radovanradic is there anything we can do to get this test running and passing?

**Comment by radovanradic** [comment]
Completed by #550
