### ISSUE TITLE
Fix disabled tests for HTTP Server TCK for Azure Functions

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-azure#577]
### Issue description

Reenable and fix the following TCK tests:

module: `test-suite-http-server-tck-azure-function-http`: `AzureFunctionHttpHttpServerTestSuite`
- [x] io.micronaut.http.server.tck.tests.RequestUriContainsQueryValueTest
- [x] io.micronaut.http.server.tck.tests.RequestUriTest
- [ ] io.micronaut.http.server.tck.tests.FilterProxyTest
- [x] io.micronaut.http.server.tck.tests.HeadersTest

module: `test-suite-http-server-tck-azure-function-http-test`: `AzureFunctionHttpTestHttpServerTestSuite`
- [x] io.micronaut.http.server.tck.tests.RequestUriContainsQueryValueTest
- [x] io.micronaut.http.server.tck.tests.RequestUriTest
- [ ] io.micronaut.http.server.tck.tests.FilterProxyTest
- [x] io.micronaut.http.server.tck.tests.HeadersTest

> @sdelamo 
>  start with the RequestUri tests
I assume we can fix both RequestUriCotnaisnQueryValue and RequestUriTest in the same PR
both for function-http and function-http-test

**Comment by wetted** [comment]
It looks like the `FilterProxyTest` needs a resolution described here: https://github.com/micronaut-projects/micronaut-core/issues/9725

**Comment by sdelamo** [comment]
@timyates see if you can review which is the status of the TCK coverage in azure.

**Comment by timyates** [comment]
Everything but `"io.micronaut.http.server.tck.tests.FilterProxyTest"` works, and as we don't have https://github.com/micronaut-projects/micronaut-core/issues/9725 we cannot get it to work

Think we should maybe close this, and address FilterProxyTest when it's possible to fix it
